apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  AUTH_PORT: "4001"
  PREDICTION_PORT: "4002"
  GATEWAY_PORT: "4000"
  AI_INFERENCE_PORT: "8000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  PREDICTION_SERVICE_URL: "http://prediction-service:4002"
  AI_INFERENCE_SERVICE_URL: "http://ai-inference-service:8000"
  AI_MODEL_NAME: "demo-sentiment-v1"

